default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username:
  password:

development:
  <<: *default
  database: ships_dev

production:
  <<: *default
  database: ships_prod
